@endpoint = https://3picvbypwl.execute-api.eu-west-1.amazonaws.com/prod/

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlckBhLnB0IiwiaWF0IjoxNjUzOTA2MTcyLCJleHAiOjE2NTM5MzQ5NzJ9.K_-j9bZ2Ma4G-RrtVqPr_35aKU7Q-ho76oomWyvZvRo


OPTIONS {{endpoint}}/authentication HTTP/1.1


###
POST {{endpoint}}/authentication HTTP/1.1
Content-Type: application/json

{
  "user": "user@a.pt",
  "password": "password"
}

###
GET {{endpoint}}/pingts

###
GET {{endpoint}}/pingpy


##########
# shoes
#########
### POST shoes
POST {{endpoint}}/shoes
Authorization: {{token}}

### GET shoes
OPTIONS  {{endpoint}}/shoes?dummy=1

### GET shoes
OPTIONS {{endpoint}}/orders
Authorization: {{token}}


### GET shoess
GET {{endpoint}}/shoes?dummy=1

### GET shoes
GET {{endpoint}}/shoes?brand2=Geox
Authorization: {{token}}

### PUT shoes
PUT {{endpoint}}/shoes
Authorization: {{token}}

### DELETE shoes
DELETE {{endpoint}}/shoes
Authorization: {{token}}


##########
# orders
#########
### POST shoes
POST {{endpoint}}/orders
Authorization: {{token}}

{
    "client": "New CLient",
    "shipping": {
        "address": "Rua X",
        "city": "Lisbon",
        "zip": "1000"
    },
    "lines": [
        {
            "reference": "AD#01",
            "size": "41",
            "price": "50.20"
        }
    ]
}


### GET shoes
OPTIONS {{endpoint}}/orders
Authorization: {{token}}


### GET shoes
GET {{endpoint}}/orders
Authorization: {{token}}


### PUT shoes
PUT {{endpoint}}/orders
Authorization: {{token}}


### DELETE shoes
DELETE {{endpoint}}/orders
Authorization: {{token}}


